{
    "name": "Social links for CRM",
    "version": "1.0",
    "category": "Sales/CRM",
    "summary": "Add social links to CRM Customers",
    "description": "",
    "author": "Eduardo Miguel Firvida Donestevez",
    "license": "GPL-3",
    "depends": ["crm"],
    "data": ["views/res_partner_views.xml"],
    "assets": {},
    "installable": True,
    "application": False,
    "auto_install": False,
}
