name: Run test

on:
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_run:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: docker compose build

    - name: Run test container
      run: docker compose up odoo-tests

    - name: Stop containers
      if: always()
      run: docker compose down